version: '2'

services:
  mongo:
    image: mongo
    expose:
      - 27017

  ingress-router:
    build: ./nginx
    volumes:
      - ${PWD}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80

  strider:
    # image: dev/strider
    build: .
    environment:
      VIRTUAL_HOST: 'strider.dev'
      DB_URI: 'mongodb://mongo:27017/strider-testing'
      NODE_ENV: production
